"""
Gemini-powered legal document generation.
"""

import os

from dotenv import load_dotenv


load_dotenv()


class GeminiDocumentGenerator:
    """
    Generates legal-document drafts using Gemini.

    If Gemini is not configured and DEMO_MODE=true,
    a local demo document will be generated.
    """

    def __init__(self):

        self.api_key = os.getenv(
            "GEMINI_API_KEY",
            ""
        ).strip()

        self.model_name = os.getenv(
            "GEMINI_MODEL",
            "gemini-2.5-flash"
        ).strip()

        self.demo_mode = (
            os.getenv(
                "DEMO_MODE",
                "true"
            )
            .strip()
            .lower()
            == "true"
        )

        self.client = None

        # Initialize Gemini client
        if self.api_key:

            try:

                from google import genai

                self.client = genai.Client(
                    api_key=self.api_key
                )

            except Exception:

                self.client = None


    def generate_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        dates: str,
    ) -> str:
        """
        Generate a complete legal document.
        """

        prompt = self._build_prompt(
            document_type,
            parties,
            terms,
            dates,
        )

        # Try Gemini
        if self.client is not None and self.api_key:

            try:

                response = self.client.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                )

                generated_text = (
                    response.text or ""
                ).strip()

                if generated_text:

                    return generated_text

                raise RuntimeError(
                    "Gemini returned an empty response."
                )

            except Exception as error:

                if not self.demo_mode:

                    raise RuntimeError(
                        f"Gemini API request failed: {error}"
                    ) from error

        # Demo mode
        if self.demo_mode:

            return self._demo_document(
                document_type,
                parties,
                terms,
                dates,
            )

        raise RuntimeError(
            "Gemini is not configured. "
            "Add GEMINI_API_KEY to .env "
            "or enable DEMO_MODE."
        )


    @staticmethod
    def _build_prompt(
        document_type: str,
        parties: str,
        terms: str,
        dates: str,
    ) -> str:

        prompt = f"""
You are the document-generation engine for LegalEase.

Create a professional legal document draft based ONLY
on the user-provided information below.

Do not invent:

- Names
- Addresses
- Amounts
- Dates
- Laws
- Jurisdictions
- Obligations

if the user did not provide them.

DOCUMENT TYPE:
{document_type}

PARTIES:
{parties}

TERMS AND CONDITIONS:
{terms}

EFFECTIVE DATE:
{dates}

REQUIREMENTS:

1. Start with a clear document title.

2. Identify the parties and effective date.

3. Organize the document using numbered sections.

4. Convert the supplied terms into clear contractual clauses.

5. Use formal and readable legal drafting language.

6. Include signature blocks at the end.

7. If important information is missing,
   write [TO BE COMPLETED] instead of inventing it.

8. Do not claim that the document is legally valid
   in any specific jurisdiction.

9. End with this disclaimer:

"Draft generated by LegalEase. This document is for
informational purposes and should be reviewed by
a qualified legal professional."

Return ONLY the document text.
"""

        return prompt.strip()


    @staticmethod
    def _demo_document(
        document_type: str,
        parties: str,
        terms: str,
        dates: str,
    ) -> str:

        # Convert semicolon-separated terms into list
        term_list = [
            item.strip()
            for item in terms.split(";")
            if item.strip()
        ]

        # Create numbered clauses
        clauses = "\n".join(
            f"{index}. {term}"
            for index, term in enumerate(
                term_list,
                start=1
            )
        )

        if not clauses:

            clauses = "1. [TO BE COMPLETED]"


        return f"""
{document_type.upper()}

Effective Date:
{dates or "[TO BE COMPLETED]"}


PARTIES

This document is entered into by the following parties:

{parties or "[TO BE COMPLETED]"}


1. PURPOSE

The parties intend to establish the rights,
responsibilities, and terms associated with the
{document_type} described in this document.


2. TERMS AND CONDITIONS

{clauses}


3. GENERAL PROVISIONS

The parties agree to act in good faith and comply
with the terms specified above.

Any information not supplied by the user remains:

[TO BE COMPLETED]


4. SIGNATURES


Party 1:

Signature: ______________________________

Name: [TO BE COMPLETED]

Date: _________________________________



Party 2:

Signature: ______________________________

Name: [TO BE COMPLETED]

Date: _________________________________


Draft generated by LegalEase. This document is for
informational purposes and should be reviewed by
a qualified legal professional.
""".strip()